services:
    www:
        build: .
        ports:
            - "8080:80"
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0.38
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: mydb
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./dbinit:/docker-entrypoint-initdb.d
            - ./dbdata:/var/lib/mysql
            - ./mycustom.cnf:/etc/mysql/conf.d/custom.cnf
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links:
            - db:db
        ports:
            - "8000:80"
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            MYSQL_ROOT_PASSWORD: root
